# Generated by Django 5.2 on 2026-07-24 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0008_samlibrating_error_individual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='anchor_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='finished',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='progress_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddConstraint(
            model_name='bookshelf',
            constraint=models.UniqueConstraint(fields=('user', 'book'), name='unique_bookshelf_user_book'),
        ),
    ]
