# Generated by Django 5.2 on 2026-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0009_bookshelf_anchor_id_bookshelf_finished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='current_unit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='finished_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='total_units',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
