# Generated by Django 5.2 on 2026-07-26 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0010_bookshelf_current_unit_bookshelf_finished_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorTodayRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('reads', models.IntegerField(blank=True, null=True)),
                ('work_url', models.CharField(blank=True, max_length=512)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authortoday_rating', to='opds_catalog.book')),
            ],
        ),
    ]
