# Generated by Django 5.2 on 2026-07-31 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0011_authortodayrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantlabRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('votes', models.IntegerField(default=0)),
                ('fantlab_url', models.CharField(blank=True, max_length=512)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fantlab_rating', to='opds_catalog.book')),
            ],
        ),
        migrations.CreateModel(
            name='LitmarketRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('reads', models.IntegerField(blank=True, null=True)),
                ('litmarket_url', models.CharField(blank=True, max_length=512)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_error', models.BooleanField(default=False)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='litmarket_rating', to='opds_catalog.book')),
            ],
        ),
    ]
