from django.urls import path
from fb2parser_web import views

app_name = "fb2parser"

urlpatterns = [
    path("",                    views.dashboard,          name="dashboard"),
    path("statistics/",         views.statistics,         name="statistics"),
    path("folder-tree/",        views.folder_tree,        name="folder_tree"),
    path("folder-count/",       views.folder_count,       name="folder_count"),
    path("main-scan/start/",    views.main_scan_start,    name="main_scan_start"),
    path("main-scan/status/",   views.main_scan_status,   name="main_scan_status"),
    path("scan-results/",       views.scan_results,       name="scan_results"),
    path("genre-books/",        views.genre_books,        name="genre_books"),
    path("genre-names/",        views.genre_names,        name="genre_names"),
    path("assign-genre-multi/", views.assign_genre_multi, name="assign_genre_multi"),
    path("scan/",              views.scan,        name="scan"),
    path("scan/start/",        views.scan_start,  name="scan_start"),
    path("scan/status/",       views.scan_status,  name="scan_status"),
    path("normalize/",         views.normalize,        name="normalize"),
    path("normalize/start/",   views.normalize_start,  name="normalize_start"),
    path("normalize/status/",  views.normalize_status, name="normalize_status"),
    path("normalize/table/",   views.normalize_table,  name="normalize_table"),
    path("normalize/names/",          views.names_list,      name="names_list"),
    path("normalize/names/from-csv/", views.names_from_csv,  name="names_from_csv"),
    path("normalize/names/save/",         views.names_save,          name="names_save"),
    path("normalize/martyrs/",            views.martyrs_list,        name="martyrs_list"),
    path("normalize/martyrs/delete/",     views.martyrs_delete,      name="martyrs_delete"),
    path("normalize/duplicates/",         views.duplicates_find,     name="duplicates_find"),
    path("normalize/duplicates/delete/",  views.duplicates_delete,   name="duplicates_delete"),
    path("normalize/compiler/scan/",      views.compiler_scan,       name="compiler_scan"),
    path("normalize/compiler/run/",       views.compiler_run,        name="compiler_run"),
    path("normalize/compiler/status/",    views.compiler_status,     name="compiler_status"),
    path("normalize/names/check-online/", views.names_check_online,  name="names_check_online"),
    path("sync/",              views.sync,             name="sync"),
    path("sync/start/",        views.sync_start,       name="sync_start"),
    path("sync/status/",       views.sync_status,      name="sync_status"),
    path("server-restart/",    views.server_restart,     name="server_restart"),
    path("browse/",            views.browse_folders,     name="browse"),
    path("genre-assign/",        views.genre_assign,        name="genre_assign"),
    path("genre-assign/start/",  views.genre_assign_start,  name="genre_assign_start"),
    path("genre-assign/status/", views.genre_assign_status, name="genre_assign_status"),
    path("archive/",      views.archive,     name="archive"),
    path("database/",     views.database,    name="database"),
    path("genres/",       views.genres,      name="genres"),
    path("log/",          views.log,         name="log"),
    path("search/",       views.search,      name="search"),
    path("new-books/",    views.new_books,   name="new_books"),
    path("series-gaps/",  views.series_gaps, name="series_gaps"),
    path("integrity/",    views.integrity,   name="integrity"),
    path("settings/",         views.fb2parser_settings, name="fb2parser_settings"),
    path("settings/list/",    views.settings_list_op,   name="settings_list_op"),
    path("settings/conv/",    views.settings_conv_op,   name="settings_conv_op"),
]
