# Generated by Django 5.2.17 on 2026-10-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0012_fantlabrating_litmarketrating'),
        ('sopds_web_backend', '0002_telegramlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmt', models.CharField(max_length=8)),
                ('filesize', models.IntegerField(default=0)),
                ('file_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_files', to='opds_catalog.book')),
            ],
            options={
                'verbose_name': 'Telegram file',
                'verbose_name_plural': 'Telegram files',
                'constraints': [models.UniqueConstraint(fields=('book', 'fmt'), name='telegram_file_book_fmt')],
            },
        ),
    ]
